//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartoteka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BAZABBIBLIOTEKAEntities : DbContext
    {
        public BAZABBIBLIOTEKAEntities()
            : base("name=BAZABBIBLIOTEKAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_loans> Book_loans { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Readers> Readers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
