//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartoteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_name
    {
        public int id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
